### ISSUE TITLE
About the nintendo switch game

### ISSUE THREAD

**Issue by zellfy** [Perfare/Il2CppDumper#115]
终于碰到来自中国的大佬~
大佬，看到你更新了nso的支持，我就下载了4.2.3版本，但是我看提示是27天前上传的，不知道是否能够支持nso，如果支持的话，我现在报错是这样的，您能帮我看看吗？
![image](https://user-images.githubusercontent.com/45615697/54686376-19945b80-4b54-11e9-91e0-de2533a1399b.png)

**Comment by zellfy** [comment]
Initializing metadata...
System.Exception: ERROR: il2cpp file not supported.
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 77
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 65
Press any key to exit...

**Comment by Perfare** [comment]
还没发布到release里，到这里下载https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts
