### ISSUE TITLE
Crash when creating dummy dll

### ISSUE THREAD

**Issue by not-matthias** [Perfare/Il2CppDumper#129]
- Il2CppDumper version: v4.5.3

- Target Unity version: 2018.2

- Mode: Auto (Plus)

- Describe the issue:  I get valid script.py and dump.cs files, but it always crashes when trying to create the dummy dll. 

- Output: 

```
Input Unity version (Just enter the first two numbers eg. 5.6, 2017.1):
2018.2
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Initializing il2cpp file...
Applying relocations...
Searching...
ERROR: This file has been protected.
CodeRegistration : 2d03210
MetadataRegistration : 2d03248
Dumping...
Done !
Create DummyDll...
System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppDumper.DummyAssemblyCreator..ctor(Metadata metadata, Il2Cpp il2cpp) in C:\projects\il2cppdumper\Il2CppDumper\DummyAssemblyCreator.cs:line 253
   at Il2CppDumper.Program.Dump() in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 656
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 88
Press any key to exit...
```

- Upload executable file and global-metadata.dat
[libil2cpp.so](https://send.firefox.com/download/06271fb21d683ac0/#g6Jb_HvuDKtvinbKJOeMJA)
[global-metadata.dat](https://send.firefox.com/download/147e8d5aa3592e69/#y6QS7jt2jAgJr0Nw92VvkA)

**Comment by Hamzabbk** [comment]
Use IL2CPP DUMPER GUI Version

**Comment by KhaBib290** [comment]
Recently i tried to dump Il2cpp lib file & it's version is 29. I successfully get dump.cs file and structure but there is an error in generate dummy dll file. It shows the following problem - 

System.Exception: Invalid compressed integer format
   at Il2CppDumper.BinaryReaderExtensions.ReadCompressedUInt32(BinaryReader reader)
   at Il2CppDumper.BinaryReaderExtensions.ReadCompressedInt32(BinaryReader reader)
   at Il2CppDumper.Il2CppExecutor.GetConstantValueFromBlob(Il2CppTypeEnum type, BinaryReader reader, BlobValue& value)
   at Il2CppDumper.Il2CppExecutor.TryGetDefaultValue(Int32 typeIndex, Int32 dataIndex, Object& value)
   at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor, Boolean addToken)
   at Il2CppDumper.DummyAssemblyExporter.Export(Il2CppExecutor il2CppExecutor, String outputDir, Boolean addToken)
   at Il2CppDumper.FormGUI.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir)
   at Il2CppDumper.FormGUI.Dumper(String file, String metadataPath, String outputPath)
