### ISSUE TITLE
Issue handling dumped elf

### ISSUE THREAD

**Issue by sanktanglia** [Perfare/Il2CppDumper#141]
Im working on a new mobile game where both the il2cpp.so and meta data file are obfuscated. I have dumped both of them from memory. The meta data file loads properly, but the dumped so file doesnt appear to have section headers. When its asking for dump address, is this the address in memory the dump was at? Attached are the meta data files and so
https://www.mediafire.com/file/wvd86ylap5o2hez/recombined_code.so/file
https://www.mediafire.com/file/wdsxg6rja1bsas4/metadata.bin.bin/file

**Comment by sanktanglia** [comment]
Whoops i was testing on the wrong .so file, attaching the new one. Now it will begin to dump if I provide the offset(0xd22b7000) but crashes
Input Unity version (Just enter the first two numbers eg. *.*, ****.*):
2018.3
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Initializing il2cpp file...
Detected this may be a dump file. If not, it must be protected.
Input dump address:
0xd22b7000
Note that in this state, the Offset of the output is actually RVA.
Applying relocations...
Searching...
CodeRegistration : 20a1f34
MetadataRegistration : d4380694
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Program.GetTypeName(Il2CppTypeDefinition typeDef) in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 748
   at Il2CppDumper.Program.GetTypeName(Il2CppType type, Boolean fullName) in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 704
   at Il2CppDumper.Program.GetTypeName(Il2CppTypeDefinition typeDef) in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 748
   at Il2CppDumper.Program.GetTypeName(Il2CppType type, Boolean fullName) in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 704
   at Il2CppDumper.Program.Dump() in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 565
   at Il2CppDumper.Program.Main(String[] args) in C:\Users\nesin\Downloads\Il2CppDumper-master\Il2CppDumper-master\Il2CppDumper\Program.cs:line 88
Press any key to exit...

https://www.mediafire.com/file/wvd86ylap5o2hez/recombined_code.so/file

**Comment by sanktanglia** [comment]
Closing this as i found a unity version that works for this, just had to try them all
