### ISSUE TITLE
System.Exception: ERROR: Can't use any mode

### ISSUE THREAD

**Issue by parind** [Perfare/Il2CppDumper#209]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
5.0.0

- Target Unity version
2018.2

- Describe the issue
```
Initializing metadata...
Initializing il2cpp file...
Applying relocations...
Select Mode: 1.Manual 2.Auto 3.Auto(Plus) 4.Auto(Symbol)
Searching...
System.Exception: ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, String stringVersion, Int32 mode, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 261
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 85
```

- Upload executable file and global-metadata.dat
[sample.zip](https://www90.zippyshare.com/v/4yHyr5b8/file.html)

**Comment by Perfare** [comment]
Auto mode works fine

**Comment by marcocorriero** [comment]
@Perfare got the same issue here.
