### ISSUE TITLE
Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by LyonGu** [Perfare/Il2CppDumper#236]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
v6.0.3
- 目标Unity版本
2018.2.10f1
- 问题描述
文件是从ipa中提取的。执行.\Il2CppDumper.exe D:\temp\earthglobewiki D:\temp\global-metadata.dat输出如下日志，与[issue#235](https://github.com/Perfare/Il2CppDumper/issues/235)的输出日志不一样。
Initializing metadata...
Metadata Version: 21
Select Platform: 1.32bit 2.64bit
Initializing il2cpp file...
Il2Cpp Version: 21
Searching...
CodeRegistration : f14564
MetadataRegistration : f22904
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Il2Cpp.cs:line 56
   at Il2CppDumper.Macho.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho.cs:line 64
   at Il2CppDumper.Il2Cpp.AutoInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Il2Cpp.cs:line 49
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 179
ERROR: An error occurred while processing.
- 上传可执行文件和global-metadata.dat
因github上传文件大小限制，上传至网盘。[下载地址](https://send.firefox.com/download/5be23211c9201bcb/#vaXa9jevWceQfTIi8p9zAg)

**Comment by LyonGu** [comment]
ipa是从appstore下载的，刚查到appstore会对ipa会加壳，有可能是这个原因。如果是的话，请关掉此issue。

**Comment by Perfare** [comment]
请使用越狱设备然后使用[frida-ios-dump](https://github.com/AloneMonkey/frida-ios-dump)或者[Clutch](https://github.com/KJCracks/Clutch)获取解密后的ipa
