### ISSUE TITLE
Index was outside the bounds of the array

### ISSUE THREAD

**Issue by SGprooo** [Perfare/Il2CppDumper#308]
Currently on the latest Il2CppDumper release, Il2Cpp shows Version: 24.1

Target Unity version is 2018.4.10f1, but Il2CppDumper did not ask for text inputs. (improvement)

To extend the error shown on the title, I'll paste the full error here.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 72
   at Il2CppDumper.Il2Cpp.AutoInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 65
   at Il2CppDumper.Program.Init(Byte[] il2cppBytes, Byte[] metadataBytes, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 174
ERROR: An error occurred while processing.

The executable and metadata have been decrypted, here are the files.
[Meta+Exec.zip](https://github.com/Perfare/Il2CppDumper/files/4749335/Metadata.zip)

**Comment by Perfare** [comment]
Use the file you provided without any problems.
