### ISSUE TITLE
Ghidra Scripting Issue

### ISSUE THREAD

**Issue by GodGyunpil** [Perfare/Il2CppDumper#316]
Whenever i run ghidra.py in Ghidra after opening the script.json file, I get the following error.
What is the problem?

Traceback (most recent call last):
  File "C:\Users\directory\ghidra_scripts\ghidra.py", line 44, in <module>
    set_name(addr, name)
  File "C:\Users\directory\ghidra_scripts\ghidra.py", line 21, in set_name
    createLabel(addr, name, True, USER_DEFINED)
	at ghidra.program.model.symbol.SymbolUtilities.validateName(SymbolUtilities.java:239)
	at ghidra.program.database.symbol.SymbolManager.validateName(SymbolManager.java:2513)
	at ghidra.program.database.symbol.SymbolManager.createCodeSymbol(SymbolManager.java:2354)
	at ghidra.program.database.symbol.SymbolManager.createLabel(SymbolManager.java:2335)
	at ghidra.program.flatapi.FlatProgramAPI.createLabel(FlatProgramAPI.java:426)
	at jdk.internal.reflect.GeneratedMethodAccessor33.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
ghidra.util.exception.InvalidInputException: ghidra.util.exception.InvalidInputException: Symbol name contains invalid characters: System.Collections.Generic.Dictionary<InternalProtocol,-TcpClient.>$$.ctor
ghidra.py> Finished!

**Comment by Perfare** [comment]
It seems that some special symbols Ghidra does not support.
Upload the source file and I will check it.

**Comment by Perfare** [comment]
#287
