### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException on Maze

### ISSUE THREAD

**Issue by GoobyCorp** [Perfare/Il2CppDumper#318]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.3.1

- Target Unity version
2020.1.0.21929

- Describe the issue
This appears to work in 6.2.1 but not in anything above that.
`Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 180a10e10
MetadataRegistration : 180a10e80
Change il2cpp version to: 24.3
Actual CodeRegistration : 180a10e00
Dumping...
Done!
Generate script...
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary2.get_Item(TKey key)
   at Il2CppDumper.ScriptGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:line 158
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 227
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 95
Press any key to exit...`

- Upload executable file and global-metadata.dat
[Here](https://mega.nz/file/4s5B0CTI#KOLvlZEmyM4ibdyNoO5siG8k0ZB9fELI7uPJMs0Jt6I)

**Comment by Perfare** [comment]
Pc game executable file is GameAssembly.dll, not .exe file.

**Comment by GoobyCorp** [comment]
Sorry, [here](https://mega.nz/file/90onXAJa#B-b410dnDcFmTpDHM4iJ_UhcvrtnlsxmYbWfw6cvMsg).

**Comment by Perfare** [comment]
Already fixed.
