### ISSUE TITLE
ERROR: This file may be protected.

### ISSUE THREAD

**Issue by samsharam** [Perfare/Il2CppDumper#328]
`Initializing metadata...

Metadata Version: 23

Initializing il2cpp file...

Applying relocations...

WARNING: find .init_proc

ERROR: This file may be protected.

Il2Cpp Version: 23

Searching...

CodeRegistration : 607cd3c

MetadataRegistration : 607cd74

System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 75

   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 68

   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in 
C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 183

ERROR: An error occurred while processing.

Press any key to exit...
`

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-this-file-may-be-protected

**Comment by samsharam** [comment]
Thank you so much, I want to contribute, can we connect ?
