### ISSUE TITLE
Make dump.cs OK but make DummyDLL has error "Index was outside the bounds of the array"

### ISSUE THREAD

**Issue by JustDragon** [Perfare/Il2CppDumper#345]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.4.4

- Target Unity version: 2018.4.15f1

- Describe the issue: Dumper can make dump.cs fine, but when make DummyDLL, it has this error

> Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 55d4340
MetadataRegistration : 55d4378
Dumping...
Done!
Generate script...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.ScriptGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:line 41
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 233
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 95
Press any key to exit...

- Upload executable file and global-metadata.dat: https://mega.nz/file/CNdGTIjS#Ap2_0x5Xj_8dhCjCaFwsxNsZAzIle2T2U2rUhHKlODs

**Comment by Perfare** [comment]
Fixed.
