### ISSUE TITLE
"Detected this may be a dump file" (but isn't a dump)

### ISSUE THREAD

**Issue by yvsdrop** [Perfare/Il2CppDumper#359]
- Il2CppDumper version: 6.4.12
- Target Unity version: 2019.2.21f1 
- Describe the issue
```
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
0
Applying relocations...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 2ddc310
MetadataRegistration : 2ddc3cc
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate script...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
	at Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 146
	at Il2CppDumper.ScriptGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:line 710
	at Il2CppDumper.ScriptGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\ScriptGenerator.cs:line 48
	at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 241
	at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 96
```
It asked for the dump address, but the il2cpp.so was not from a memory dump but just from the apk, so I just put 0. Unlike some other issues reported before, this did not tell me that it might be protected, and I checked the .so file and it started with the correct 4 bytes (0x7F ELF). But maybe it has a different kind of protection? I'm not sure.
- Upload executable file and global-metadata.dat
[il2cpp&metadata.zip](https://github.com/Perfare/Il2CppDumper/files/5185717/il2cpp.metadata.zip)

**Comment by Perfare** [comment]
This file should be protected.
