### ISSUE TITLE
Metadata file supplied is not valid metadata file

### ISSUE THREAD

**Issue by HellGate94** [Perfare/Il2CppDumper#377]
- Il2CppDumper version
v6.4.12

- Target Unity version
likely 2017.4.30

- Describe the issue
```
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 51
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 119
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 94
```

- Upload executable file and global-metadata.dat
can't publicly share for legal and file size reasons
game tested is Genshin Impact

**Comment by Perfare** [comment]
https://github.com/Perfare/Il2CppDumper#error-metadata-file-supplied-is-not-valid-metadata-file
