### ISSUE TITLE
All modes does not work on some game

### ISSUE THREAD

**Issue by evildog1** [Perfare/Il2CppDumper#38]
I found a game that does not work with il2cppdumper. All modes failed. I know i can view function names in IDA but problem is I need to know method types, int, bool, void etc...
Game is LODE 

[il2cpp.zip](https://github.com/Perfare/Il2CppDumper/files/1535401/il2cpp.zip)

Manual mode
```
Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Elf.MapVATR(Object uiAddr) i C:\projects\il2cppdumper\Il2CppDumper\Elf.cs:line 84
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Il2CppDumper.Il2Cpp.MapVATR[T](Object uiAddr, Int64 count) i C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp.cs:line 90
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) i C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp.cs:line 33
   at Il2CppDumper.Program.Main(String[] args) i C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 104
Press any key to exit...
```

Auto mode and auto advanced
```
ERROR: Unable to process file automatically, try to use other mode.
   at Il2CppDumper.Program.Main(String[] args) i C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 94
Press any key to exit...
```

**Comment by Perfare** [comment]
I test using advanced auto mode, it's work fine

**Comment by evildog1** [comment]
hmm i didn't realize there was a new version. I updated it and it works, only advanced auto mode
