### ISSUE TITLE
Issue with dumping after code registration and meta are entered

### ISSUE THREAD

**Issue by TheOldSchoolModder** [Perfare/Il2CppDumper#380]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: Il2CppDumper v6.4.12

- Target Unity version: 2019.4.7f1

- Describe the issue: System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 198
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 100
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217

- Upload executable file and global-metadata.dat

[http://www.mediafire.com/file/6fl89huyoxewp0i/GameAssembly.rar/file](url) assembly + metadata

**Comment by Perfare** [comment]
Sorry I do not plan to support this file.
