### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by Toshiba1127** [Perfare/Il2CppDumper#397]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.4.12

- Target Unity version 2018.4.16f1

- Describe the issue 
It just won't dump. I tried given manual dump I found via IDA but still failed

![image](https://user-images.githubusercontent.com/64008639/98008649-ff74c300-1df4-11eb-985a-d2f22b3a0650.png)

```
Initializing metadata...
Metadata Version: 24,1
Initializing il2cpp file...
Il2Cpp Version: 24,1
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 107602850
Input MetadataRegistration: 1077333E8
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 uiAddr) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 73
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 124
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...
```

- Upload executable file and global-metadata.dat
https://anonymousfiles.io/DQ7sXE70/

**Comment by Perfare** [comment]
This game modified the structure of il2cpp.
