### ISSUE TITLE
Dump support for empty global-metadata.dat

### ISSUE THREAD

**Issue by WanghongLin** [Perfare/Il2CppDumper#400]
- Il2CppDumper-v6.3.3

- 2018.4.21f1

- Recently I found an Android game contain an empty `global-metadata.dat`, named `Dragalia Lost` and Android package name is `com.nintendo.zaga`. When I tried to dump this game, I got the following error message.

```
$ ../../Il2CppDumper-v6.3.3/Il2CppDumper.exe lib/arm64-v8a/libil2cpp.so assets/bin/Data/Managed/Metadata/global-metadata.dat

Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: startIndex
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.BitConverter.ToUInt32(Byte[] value, Int32 startIndex)
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 38
```

- Could you guys provide support this type of dump with an empty `global-metadata.dat` file?

**Comment by Perfare** [comment]
You need to find out where global-metadata.dat is hidden.
