### ISSUE TITLE
邦多利3.8.0+出点新问题，dump.cs正常但有报错，DummyDll失败

### ISSUE THREAD

**Issue by esterTion** [Perfare/Il2CppDumper#407]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
> 6.4.12
- 目标Unity版本
> 2019.4.11f1
- 问题描述
邦多利的3.8.0之后好像会炸？但是dump.cs可以输出，DummyDll没了。
我拿来看个proto结构和取个versionHash是没啥问题，不知道是不是新版又改了东西。
上个月出3.8.0之后我给忘了，今天更了3.9.0，才想起来（
<details>
<summary>Console Log</summary>

```
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
Change il2cpp version to: 24.3
CodeRegistration : 2e78f10
MetadataRegistration : 2f3b480
Dumping...
ERROR: Some errors in dumping
Done!
Generate script...
Done!
Generate dummy dll...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 uiAddr) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 73
   at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor) in C:\projects\il2cppdumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 270
   at Il2CppDumper.DummyAssemblyExporter.Export(Il2CppExecutor il2CppExecutor, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\DummyAssemblyExporter.cs:line 20
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 247
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 96
Press any key to exit...
```

</details>

- 上传可执行文件和global-metadata.dat
[GDrive](https://drive.google.com/file/d/1kEyZ4-xKRu60wVQng9IS9XwTJwI0XBCV/view?usp=sharing)

**Comment by Perfare** [comment]
这个bug实际上已经修了 f8b509c2d851cfbc65c565b3f0c30ce6ecdbb0e2，只是没有release，https://ci.appveyor.com/project/Perfare/il2cppdumper/branch/master/artifacts

**Comment by esterTion** [comment]
诶？我记得之前第一次在Phigros看到Framework式加载时候没问题，是不是记错了。
搞不懂unity搞这样编译干啥，uikit匹配的插件都没法自动注入了🤔

**Comment by Perfare** [comment]
换成Framework后空数组的指针可能会指向未初始化的__bss段导致报错，并不是所有游戏都有这种情况

**Comment by esterTion** [comment]
这样，理解了
