### ISSUE TITLE
Create DummyDll -> BUG: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JustDragon** [Perfare/Il2CppDumper#42]
Here is the files: http://www119.zippyshare.com/v/GqFS2150/file.html

> Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
Applying relocations...
Searching...
CodeRegistration : 18b3a3c
MetadataRegistration : 18c72f4
Dumping...
Done !
Create DummyDll...
Object reference not set to an instance of an object.
   at Il2CppDumper.DummyAssemblyCreator.GetTypeReference(MemberReference memberReference, Il2CppType pType) in C:\projects\il2cppdumper\Il2CppDumper\DummyAssemblyCreator.cs:line 223
   at Il2CppDumper.DummyAssemblyCreator..ctor(Metadata metadata, Il2Cpp il2cpp) in C:\projects\il2cppdumper\Il2CppDumper\DummyAssemblyCreator.cs:line 97
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 451
Press any key to exit...

**Comment by JustDragon** [comment]
Thank you very much for your quick fix!
