### ISSUE TITLE
System.IO.EndOfStreamException: Unable to read beyond the end of the stream

### ISSUE THREAD

**Issue by QVA0Rg** [Perfare/Il2CppDumper#430]
- Il2CppDumper v6.5.0

- Target Unity version 2019.4.21f1

- Describe the issue

`Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Applying relocations...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 10d4a14
MetadataRegistration : 10d4e6c
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Il2CppDumper.BinaryStream.ReadPrimitive(Type type) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 122
   at Il2CppDumper.BinaryStream.ReadClass[T]() in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 142
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 201
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 110
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 67
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 190
ERROR: An error occurred while processing.
Press any key to exit...`

- Upload executable file and global-metadata.dat

[example1.zip](https://github.com/Perfare/Il2CppDumper/files/6078950/example1.zip)
[example2.zip](https://github.com/Perfare/Il2CppDumper/files/6078951/example2.zip)

Is this a protect or a bug in the program?

**Comment by trialman** [comment]
same problem 

Il2CppDumper v6.5.0
Target Unity version 2019.4.21f1

**Comment by AndnixSH** [comment]
Same problem. I believe 2019.4.21f1 hasn't been supported yet

https://play.google.com/store/apps/details?id=com.os.falcon.yogame.stickfighter&hl=en&gl=us

**Comment by QVA0Rg** [comment]
Yes, all games with unity version 2019.4.21f1 don't dump

**Comment by Perfare** [comment]
New il2cpp version, now supported.
