### ISSUE TITLE
Il2cpp is unable to decrypt

### ISSUE THREAD

**Issue by Barshan-Mandal** [Perfare/Il2CppDumper#441]
- Il2CppDumper version
6.5.3
- Target Unity version
2018.4.11f1
- Describe the issue
Initializing metadata...
Metadata Version: 24.1
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 417bcc8
MetadataRegistration : 417bd38
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 85
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 76
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
ERROR: An error occurred while processing.
- Upload executable file and global-metadata.dat
[saaddszxfcsdzxfc.zip](https://github.com/Perfare/Il2CppDumper/files/6202379/saaddszxfcsdzxfc.zip)

**Comment by Perfare** [comment]
> WARNING: find .init_proc
ERROR: This file may be protected.
