### ISSUE TITLE
Sequence contains no matching element - Unity game on iOS

### ISSUE THREAD

**Issue by ja5er** [Perfare/Il2CppDumper#444]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.5.3

- Target Unity version
2020.02

- Describe the issue
I dumped a Unity game from an iPhone and tried to dump unity symbols for it but I run into an error - `Sequence contains no matching element`.

```
dotnet ./Il2CppDumper/bin/Debug/netcoreapp3.1/Il2CppDumper.dll ./UnityFramework ./global-metadata.dat /tmp/

Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 4513858
MetadataRegistration : 46377d0
Change il2cpp version to: 27.1
CodeRegistration : 4513850
Dumping...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 uiAddr) in unity/Il2CppDumper/Il2CppDumper/ExecutableFormats/Macho64.cs:line 72
   at Il2CppDumper.Il2CppExecutor..ctor(Metadata metadata, Il2Cpp il2Cpp) in unity/Il2CppDumper/Il2CppDumper/Utils/Il2CppExecutor.cs:line 46
   at Il2CppDumper.Program.Du


mp(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in unity/Il2CppDumper/Il2CppDumper/Program.cs:line 239
   at Il2CppDumper.Program.Main(String[] args) in unity/Il2CppDumper/Il2CppDumper/Program.cs:line 102
Press any key to exit...
```

- Upload executable file and global-metadata.dat
[Framerowks/UnityFramework.framework/UnityFramework and global-metadata.dat](https://drive.google.com/file/d/14xXJ_9JZWFvBuCYCWCp7t-y1lM5HV4t2/view?usp=sharing) (iOS app)

**Comment by Perfare** [comment]
same as #439 ,fixed.
