### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by lolBoi9696** [Perfare/Il2CppDumper#448]
it wont let me get any code from a obfuscated game now i dont care if the code is obfuscated i just need it so i can reference some classes? 
this is the error i get 

`System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Il2CppDumper.BinaryStream.ReadPrimitive(Type type) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 123
   at Il2CppDumper.BinaryStream.ReadClass[T]() in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 143
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 213
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 131
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 224
ERROR: An error occurred while processing.
Press any key to exit...`

it wants me to type in a metadata registration and a code registration but idk how to get that from the game

**Comment by lolBoi9696** [comment]
wow thanks for leaving nothing lol
