### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by benny-cz** [Perfare/Il2CppDumper#467]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

v6.6.2

- Target Unity version

2018.2.5f1

- Describe the issue

System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Elf.MapVATR(UInt64 addr) in E:\BareBit\Il2CppDumper\Il2CppDumper\ExecutableFormats\Elf.cs:line 82
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in E:\BareBit\Il2CppDumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 136
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in E:\BareBit\Il2CppDumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 77
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in E:\BareBit\Il2CppDumper\Il2CppDumper\Program.cs:line 198
ERROR: An error occurred while processing.

[files.zip](https://github.com/Perfare/Il2CppDumper/files/6560653/files.zip)

- Upload executable file and global-metadata.dat

**Comment by mazegen** [comment]
Note: the `il2cpp.so` was built from the offical Unity Example project using official Unity. There are no modifications to the IL2CPP structures.

**Comment by Perfare** [comment]
This file can be processed normally without any problems.
