### ISSUE TITLE
ERROR: il2cpp file not supported.

### ISSUE THREAD

**Issue by sifrah** [Perfare/Il2CppDumper#470]
Hello Guys

- Il2CppDumper version -> 6.6.2

- Target Unity version -> 2019.4.17f1

- Describe the issue -> Cannot dump libil2cpp.so and global-metadata.dat. 
When I exract libil2cpp.so from gameguardian I got this error -> 
```
C:\Users\myuser\Desktop\h>Il2CppDumper.exe libil2cpp.so global-metadata.dat output
Initializing metadata...
Metadata Version: 24,2
Initializing il2cpp file...
System.NotSupportedException: ERROR: il2cpp file not supported.
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...
```
When i try to dump the original file, i got this error ->
```
C:\Users\myuser\Desktop\h>Il2CppDumper.exe libil2cpp1.so global-metadata.dat output
Initializing metadata...
Metadata Version: 24,2
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 24,2
Searching...
CodeRegistration : 0
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration:
```
How to get the CodeRegistration and MetadataRegistration please ?
[files.zip](https://github.com/Perfare/Il2CppDumper/files/6594503/files.zip) 
Thanks a lot for your help

**Comment by Krdevjs** [comment]
hi didi u find way

**Comment by sifrah** [comment]
no, ragequit...
