### ISSUE TITLE
ERROR: Can't use auto mode to process file, try manual mode.

### ISSUE THREAD

**Issue by tellowkrinkle** [Perfare/Il2CppDumper#472]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
2d70941e03a2156d819d87d03ade94116e00f140

- Target Unity version
2019.3.13 (Nintendo Switch)

- Describe the issue
When attempting to process, I get the following result:
<details>

```
Initializing metadata...
Metadata Version: 24.2
Initializing il2cpp file...
Il2Cpp Version: 24.2
Searching...
CodeRegistration : 449aca0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
```
</details>

I'm pretty sure the proper locations are `449ac90` and `449b0d8`, and if I input those it gets fairly far but eventually crashes:
<details>

```
Input CodeRegistration: 449ac90
Input MetadataRegistration: 449b0d8
Change il2cpp version to: 24.3
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in /private/tmp/Il2CppDumper/Il2CppDumper/Utils/Il2CppExecutor.cs:line 61
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in /private/tmp/Il2CppDumper/Il2CppDumper/Utils/Il2CppExecutor.cs:line 103
   at Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) in /private/tmp/Il2CppDumper/Il2CppDumper/Utils/Il2CppExecutor.cs:line 152
   at Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) in /private/tmp/Il2CppDumper/Il2CppDumper/Outputs/StructGenerator.cs:line 870
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in /private/tmp/Il2CppDumper/Il2CppDumper/Outputs/StructGenerator.cs:line 49
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in /private/tmp/Il2CppDumper/Il2CppDumper/Program.cs:line 248
   at Il2CppDumper.Program.Main(String[] args) in /private/tmp/Il2CppDumper/Il2CppDumper/Program.cs:line 102
Press any key to exit...
```
</details>

- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/6660851/files.zip)

**Comment by bwilmott** [comment]
I get the same issue when trying to use this program for PokeOne

**Comment by Perfare** [comment]
The structure of il2cpp has been modified to prevent dumping.
