### ISSUE TITLE
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[7564520]

### ISSUE THREAD

**Issue by Gourov** [Perfare/Il2CppDumper#478]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version : 6.6.3

- Target Unity version : 19.3.13f1

- Describe the issue : I got this message below.
- `Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[7564520].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 38
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...`

- Upload executable file and global-metadata.dat
[meta and lib.zip](https://github.com/Perfare/Il2CppDumper/files/6748929/meta.and.lib.zip)

**Comment by Perfare** [comment]
Encrypted Metadata.
