### ISSUE TITLE
please help me~

### ISSUE THREAD

**Issue by weihaiwh** [Perfare/Il2CppDumper#507]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
6.6.5
- 目标Unity版本
2018.4.35f1 
- 问题描述
it show: ERROR: Some errors in dumping
Done!
Generate struct...
System.ArgumentOutOfRangeException: Stream length must be non-negative and less than 2^31 - 1 - origin.
Parameter name: value
   at System.IO.MemoryStream.set_Position(Int64 value)
   at Il2CppDumper.BinaryStream.ReadStringToNull(UInt64 addr) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 227
   at Il2CppDumper.Metadata.GetStringFromIndex(UInt32 index) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 147
   at Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 154
   at Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 880
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 51
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 248
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
Press any key to exit...

- 上传可执行文件和global-metadata.dat
https://github.com/weihaiwh/ohayoo_1.3.0_CrackerXI.git

**Comment by Perfare** [comment]
global-metadata.dat文件结构被修改
