### ISSUE TITLE
HELP!

### ISSUE THREAD

**Issue by StrikcYT** [Perfare/Il2CppDumper#522]
Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[920093868].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 38
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...

I read that it is possible manually, but how

**Comment by StrikcYT** [comment]
https://dropmefiles.com/277117
