### ISSUE TITLE
Unable to read beyond the end of the stream for il2cpp v27 dump 2021.1.21f1

### ISSUE THREAD

**Issue by david8557** [Perfare/Il2CppDumper#527]
- Il2CppDumper version: 6.6.5

- Target Unity version: 2021.1.21f1

- Describe the issue: il2cpp base: 0x6f8b040000, meta base: 0x6f6f60b000

> Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
0x6f8b040000
Il2Cpp Version: 27
Input global-metadata.dat dump address:
0x6f6f60b000
Searching...
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.__Error.EndOfFile()
   at System.IO.BinaryReader.FillBuffer(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt64()
   at Il2CppDumper.SectionHelper.FindReference(UInt64 addr) in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 359
   at Il2CppDumper.SectionHelper.FindCodeRegistration2019() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 339
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf64.cs:line 93
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
ERROR: An error occurred while processing.
Press any key to exit...

- Upload executable file and global-metadata.dat: https://www11.zippyshare.com/v/KidUukhF/file.html

**Comment by Perfare** [comment]
It seems that you did not dump a section or other reasons, but it doesn’t matter, that section of data is not important, as long as you modify the following data
![捕获](https://user-images.githubusercontent.com/12952226/144328845-d5abeb19-a8ca-4da2-a48a-2531b213591f.PNG)
This is the modified file 
[libil2cpp_dump_6f8b040000.zip](https://github.com/Perfare/Il2CppDumper/files/7637666/libil2cpp_dump_6f8b040000.zip)

**Comment by david8557** [comment]
@Perfare I dump this lib with GG. Can you please help me explain how to know the correct value is 6625184 for Elf64_Xword p_memsz_SEGMENT_RAM_LENGTH. and 473EC50h for Elf64_Off p_offset_FROM_FILE_BEGIN?
Thank you a lot!
