### ISSUE TITLE
Index was outside the bounds of the array when dump Metadata version[29]

### ISSUE THREAD

**Issue by LeoMaster9x** [Perfare/Il2CppDumper#544]
- Il2CppDumper version:  6.7.2

- Describe the issue: Index was outside the bounds of the array when dump Metadata version[29]

- File and global-metadata.dat: [https://drive.google.com/file/d/1yVUqXmzrfey2Lml5N4R24cmK4Yjpjh1W/view?usp=sharing](url)

**Error when dump**
```
CodeRegistration : 24db9c4
MetadataRegistration : 255b160
Dumping...
ERROR: Some errors in dumping
Done!
Generate struct...
Done!
Generate dummy dll...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2CppExecutor.GetConstantValueFromBlob(Il2CppTypeEnum type, BinaryReader reader, BlobValue& value) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 345
   at Il2CppDumper.CustomAttributeDataReader.ReadAttributeDataValue() in C:\projects\il2cppdumper\Il2CppDumper\Utils\CustomAttributeDataReader.cs:line 148
   at Il2CppDumper.CustomAttributeDataReader.VisitCustomAttributeData() in C:\projects\il2cppdumper\Il2CppDumper\Utils\CustomAttributeDataReader.cs:line 119
   at Il2CppDumper.DummyAssemblyGenerator.CreateCustomAttribute(Il2CppImageDefinition imageDef, Int32 customAttributeIndex, UInt32 token, ModuleDefinition moduleDefinition, Collection`1 customAttributes) in C:\projects\il2cppdumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 589
   at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 386
   at Il2CppDumper.DummyAssemblyExporter.Export(Il2CppExecutor il2CppExecutor, String outputDir, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\DummyAssemblyExporter.cs:line 20
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 254
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
Press any key to exit...
```

**Image:**
![trell2](https://user-images.githubusercontent.com/90177825/147316544-10ac07c1-863c-4dd3-84b0-0a0f5a686c88.png)

**Comment by Perfare** [comment]
already fixed.
