### ISSUE TITLE
Mono.ArgumentNullOrEmptyException: Argument null or empty when make DummyDLL

### ISSUE THREAD

**Issue by david8557** [Perfare/Il2CppDumper#548]
- Il2CppDumper version: 6.7.5

- Target Unity version: 2018.4.24f1

- Describe the issue: It has error at making DummyDLL

> Initializing il2cpp file...
Il2Cpp Version: 24.1
Searching...
CodeRegistration : 1062fc778
MetadataRegistration : 10653a730
Dumping...
Done!
Generate struct...
Done!
Generate dummy dll...
Mono.ArgumentNullOrEmptyException: Argument null or empty
Parameter name: name
   at Mono.Cecil.Mixin.CheckName(String name)
   at Mono.Cecil.AssemblyNameReference..ctor(String name, Version version)
   at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 66
   at Il2CppDumper.DummyAssemblyExporter.Export(Il2CppExecutor il2CppExecutor, String outputDir, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\DummyAssemblyExporter.cs:line 20
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 254
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 102
Press any key to exit...

- Upload executable file and global-metadata.dat: https://www94.zippyshare.com/v/ClOzsqeJ/file.html

**Comment by Perfare** [comment]
Fixed.
