### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by KarmaMod** [Perfare/Il2CppDumper#552]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: 6.7.6

- Target Unity version: 2020.3.19f1

- Describe the issue:
Dumping just failed. I have dumped both .so and metadata.dat and inputted correct addresses.

- Upload executable file and global-metadata.dat:
https://drive.google.com/file/d/1n5JF6xAqXuoEIrTw22vwq9ECtez5WKRp/view

- Log
```
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
baaec000
Il2Cpp Version: 27
Input global-metadata.dat dump address:
aa52e000
Searching...
CodeRegistration : bd40bf60
MetadataRegistration : bd40bfe0
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 197
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 136
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 91
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
ERROR: An error occurred while processing.
Press any key to exit...
```

**Comment by Perfare** [comment]
@VanHoevenTR It is already supported after [this](https://github.com/Perfare/Il2CppDumper/commit/2f1a4b2a149080a9e85ce8c1e2c1b76de8cc171d), you need to control some behavior in config file.
refer to this #598

**Comment by masagrator** [comment]
@BoomboomDada Unity is changing stuff with every release. Without access to source code, author must add compability based on what they have. Issue is not with compability with 32-bit apps, issue is that this tool is just not perfect. Create another issue otherwise author will omit your issue since you added stuff after it was closed.
