### ISSUE TITLE
getting a "ERROR: il2cpp file not supported." error when trying to dump the stream game Phasmophobia

### ISSUE THREAD

**Issue by CursedKoi** [Perfare/Il2CppDumper#560]
getting a "ERROR: il2cpp file not supported." error when trying to dump the stream game Phasmophobia

- **Il2CppDumper-v6.7.6**

- **Unity 2020.1.6**

- **metadata file for the game Phasmophobia isn't supported?** I've done some digging trying to find out what's wrong but I'm not the best computer person out there. I've tried other dumpers but all of them have the same result. originally the /managed folder was accessible from the explorer but they migrated to il2ccp about a year ago.
-
Initializing metadata...
Metadata Version: 24.4
Initializing il2cpp file...
System.NotSupportedException: ERROR: il2cpp file not supported.
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...

**- files**
[Metadata.zip](https://github.com/Perfare/Il2CppDumper/files/7893465/Metadata.zip)

**Comment by Aug-9th** [comment]
do u find problem in this error, I also have the same error, can you help me?
