### ISSUE TITLE
System.OverflowException: Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by Nii-Saan** [Perfare/Il2CppDumper#562]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
`6.7.6
`
- Target Unity version
`2020.3.18
`
- Describe the issue
```
System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 197
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 113
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 91
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 197
ERROR: An error occurred while processing.

```

- Upload executable file and global-metadata.dat
https://www.mediafire.com/file/7m5teia9rprt282/GameAssembly.zip/file

**Comment by Perfare** [comment]
already fixed.
