### ISSUE TITLE
Dumper Error

### ISSUE THREAD

**Issue by xillscar** [Perfare/Il2CppDumper#589]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
   Il2CppDumper-net6-v6.7.8

- Target Unity version
  5.6.3f1

- Describe the issue

- Upload executable file and global-metadata.dat

Metadata Version: 23
Initializing il2cpp file...
Detected this may be a dump file.
Input il2cpp dump address or input 0 to force continue:
0
Applying relocations...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Il2CppDumper.Elf.CheckProtection() in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf.cs:line 277
   at Il2CppDumper.Elf..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf.cs:line 49
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 155
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...
[input.zip](https://github.com/Perfare/Il2CppDumper/files/8374145/input.zip)

**Comment by Perfare** [comment]
Obviously this file is encrypted.
