### ISSUE TITLE
INDEX OUT OF RANGE EXCEPTION

### ISSUE THREAD

**Issue by IFEAYOMIDE** [Perfare/Il2CppDumper#603]
Il2CppDumper version: 6.4.8.0

Target Unity version: 2019.4.27f1t3

Is there a way to fix this?

> Initializing metadata...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 215
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 121
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...

**-Il2cpp**
https://drive.google.com/file/d/11wE7liEbUqLo6XR3X7-y_wOkoVp2Vopp/view?usp=drivesdk

**-global-metadata**
https://drive.google.com/file/d/12BgGXH2VNu9fopu0lOtP_qlk4lDyGWSg/view?usp=drivesdk

**Comment by IFEAYOMIDE** [comment]
I have tried the latest version of Il2cppdumper 6.7.8, still the same.

**Comment by Perfare** [comment]
Encrypted file.
