### ISSUE TITLE
Is there a way to solve this? Has the game guardian fix protected been passed // unity   ver 5.6.4 p4 

### ISSUE THREAD

**Issue by avatarsxr** [Perfare/Il2CppDumper#616]
dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Il2CppDumper.Metadata.ProcessingMetadataUsage()
   at Il2CppDumper.Metadata..ctor(Stream stream)
   at Il2CppDumper.FormGUI.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp)
   at Il2CppDumper.FormGUI.Dumper(String file, String metadataPath, String outputPath)

**Comment by Perfare** [comment]
You didn't provide any files, but judging from your error message, you are using an older version.
