### ISSUE TITLE
Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by nuntax** [Perfare/Il2CppDumper#629]
- Il2CppDumper version: 6.7.19

- Target Unity version: 2020.3.17

- Describe the issue: I get the following Error Message when trying to use il2cppdumper. 
 `System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt64()
   at Il2CppDumper.SectionHelper.FindMetadataRegistrationV21() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 261
   at Il2CppDumper.SectionHelper.FindMetadataRegistration() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 179
   at Il2CppDumper.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\PE.cs:line 86
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 213
ERROR: An error occurred while processing.`

- Upload executable file and global-metadata.dat
GameAssembly: https://www.mediafire.com/file/pb4y5s8ntngg227/GameAssembly.dll/file
global-metadata: https://www.mediafire.com/file/3gunt48wfoxdlcp/global-metadata.dat/file

**Comment by nuntax** [comment]
Edited the Downloadlinks. 

New ones: 
GameAssembly: https://ufile.io/7byggkap
global-metadata: https://ufile.io/d4j58fzh

**Comment by Perfare** [comment]
File is protected by vmprotect.

**Comment by nuntax** [comment]
Okay, so you cant figure out what the error is because you cant open it in a VM? 
Understandable reason, thank you anyways :)

**Comment by nuntax** [comment]
Can i bypass this by dumping the files from memory at runtime?
And if so, how would i do this?
