### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by cctgapp** [Perfare/Il2CppDumper#641]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.7.25
- Target Unity version
27
- Describe the issue
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Il2CppDumper.Macho64.MapVATR(UInt64 addr) in /Volumes/SSD/Developer/Tools/Il2CppDumper-6.7.25/Il2CppDumper/ExecutableFormats/Macho64.cs:line 71
   at Il2CppDumper.SectionHelper.FindMetadataRegistrationV21() in /Volumes/SSD/Developer/Tools/Il2CppDumper-6.7.25/Il2CppDumper/Utils/SectionHelper.cs:line 256
   at Il2CppDumper.SectionHelper.FindMetadataRegistration() in /Volumes/SSD/Developer/Tools/Il2CppDumper-6.7.25/Il2CppDumper/Utils/SectionHelper.cs:line 179
   at Il2CppDumper.Macho64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in /Volumes/SSD/Developer/Tools/Il2CppDumper-6.7.25/Il2CppDumper/ExecutableFormats/Macho64.cs:line 241
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in /Volumes/SSD/Developer/Tools/Il2CppDumper-6.7.25/Il2CppDumper/Program.cs:line 213

- Upload executable file and global-metadata.dat
[download](https://www.dropbox.com/s/nuss042wwrxccut/data.zip?dl=0)

**Comment by KingKong5147** [comment]
I can confirm that i am too getting this same issue!?..

**Comment by Perfare** [comment]
You did not provide global-metadata.dat.
