### ISSUE TITLE
Failing to dump during Initializing metadata

### ISSUE THREAD

**Issue by LabGuy94** [Perfare/Il2CppDumper#654]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.7.25
- Target Unity version
Unknown
- Describe the issue
When attempting to dump I come across an error. Error bellow.
```
Initializing metadata...
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 218
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 124
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
```

- Upload executable file and global-metadata.dat
https://ufile.io/jkpad7ew
https://ufile.io/draj4uty

**Comment by bluewave41** [comment]
Your game assembly doesn't exist anymore.

**Comment by LabGuy94** [comment]
I have updated my downloads

**Comment by LabGuy94** [comment]
Metadata was obfuscated

**Comment by TimurALTron** [comment]
Could you deobfuscate the metadata?: @LabGuy94
