### ISSUE TITLE
System.OverflowException: Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by Havie** [Perfare/Il2CppDumper#660]
**- Il2CppDumper version**
Il2CppDumper-v6.4.12
**- Target Unity version**
2020.3.5f1
**- Describe the issue**

System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 198
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 87
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 67
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 190
ERROR: An error occurred while processing.

**- Upload executable file and global-metadata.dat**
[Il2CPP_ErrorData.zip](https://github.com/Perfare/Il2CppDumper/files/9794732/Il2CPP_ErrorData.zip)

**Comment by Perfare** [comment]
Why not use the latest version of Il2CppDumper?
