### ISSUE TITLE
Dumper not working for SCP: Secret Lab

### ISSUE THREAD

**Issue by Frostytimbers** [Perfare/Il2CppDumper#665]
This game is IL2cpp
Found the GameAssembly.dll
Found the metadata
When I dump this happens

Initializing metadata...
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 218
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 124
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 126
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...

Any solutions?

**Comment by LabGuy94** [comment]
Metadata is "obfuscated" (not really its super simple)

**Comment by Cod4h** [comment]
> Metadata is "obfuscated" (not really its super simple)

Then if it is so simple why don't you explain it?

**Comment by LabGuy94** [comment]
> > Metadata is "obfuscated" (not really its super simple)
> 
> 
> 
> Then if it is so simple why don't you explain it?

Reverse game assembly yourself
