### ISSUE TITLE
Metadata file supplied is not a supported version[29]

### ISSUE THREAD

**Issue by AndysComing** [Perfare/Il2CppDumper#672]
Il2CppDumper version: v6.7.25

Target Unity version: 2021.3.12f1

Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[29].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 38
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 119
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 94
Press any key to exit...

Not sure what the problem is, checked with a hex editor and the metadata file does not appear encrypted.

https://drive.google.com/file/d/1Y_JItaUeMkqfA5cyO1-AF3ErJnbeysFw/view?usp=share_link

**Comment by RobertA-Dev** [comment]
Getting the same error @Perfare are you still planning on updating this?

**Comment by Perfare** [comment]
Although your title says version 29, what you provided is version 27. In addition, this error cannot occur on version 6.7.25.
