### ISSUE TITLE
System.Exception Thrown String[] args - Tried all modes

### ISSUE THREAD

**Issue by ElliotRobot20** [Perfare/Il2CppDumper#70]
Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
Searching...
Exception of type 'System.Exception' was thrown.
   at Il2CppDumper.Program.Main(String[] args) in C:\Users\Elliot\Desktop\OurWorld\Il2CppDumper-master\Il2CppDumper\Program.cs:line 113

ERROR: Can't use this mode to process file, try another mode.
   at Il2CppDumper.Program.Main(String[] args) in C:\Users\Elliot\Desktop\OurWorld\Il2CppDumper-master\Il2CppDumper\Program.cs:line 117

Dumping Walking Dead: Our World

**Comment by Perfare** [comment]
Please upload a file

**Comment by ElliotRobot20** [comment]
https://we.tl/t-lJxvWO1z1I

**Comment by ElliotRobot20** [comment]
I was able to dump using the manual method so I assume it cant find the offset correctly for Auto mode.

**Comment by Perfare** [comment]
supported after e85c8bc7cfa9a3662fa7e21ebc7162b087bc0d56
