### ISSUE TITLE
System.ComponentModel.Win32Exception (126): 找不到指定的模块。

### ISSUE THREAD

**Issue by hzm0603** [Perfare/Il2CppDumper#700]
- Il2CppDumper版本
6740

- 问题描述
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (126): 找不到指定的模块。
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...

- 上传可执行文件和global-metadata.dat
两个文件超过25MB,我上传到了网盘。
https://baiwan.lanzouw.com/ie2cV0prwrxa

**Comment by Perfare** [comment]
程序已加壳，并且引用了其他dll，你可以考虑把Il2CppDumper放到dll所在目录再运行，但是我不保证能dump

**Comment by iyzyi** [comment]
> 程序已加壳，并且引用了其他dll，你可以考虑把Il2CppDumper放到dll所在目录再运行，但是我不保证能dump

it's useful for me
