### ISSUE TITLE
ERROR: An error occurred while processing.

### ISSUE THREAD

**Issue by Elyxorus** [Perfare/Il2CppDumper#711]
- Il2CppDumper version: net7-win 4.7.40 (x86)
- Target Unity version: 2021.3.16.5719
(Thanks for awesome program)

Im selected GameAssembly.dll and global-metadata, and got error: (i install il2cppDumper to game folder)

```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 0
Input MetadataRegistration: 0
System.ArgumentException: An item with the same key has already been added. Key: 0
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 188
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 237
ERROR: An error occurred while processing.
Press any key to exit...

```

- executable file and global-metadata.dat in google drive:
https://drive.google.com/file/d/1eggVxNGzbp-U-5-8pYUEmFLxNv5J3ibF/view?usp=sharing

**Comment by Perfare** [comment]
The file is protected, try dumping the dll from memory.
