### ISSUE TITLE
Error when dumping il2cpp

### ISSUE THREAD

**Issue by sszgcruiyize** [Perfare/Il2CppDumper#718]
- Il2CppDumper version: v6.7.40

- Target Unity version (optional): I don't know

- Describe the issue: System.ArgumentException: An item with the same key has already been added. Key: 707111
at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] source, Func2 keySelector, IEqualityComparer1 comparer)
at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable1 source, Func2 keySelector, IEqualityComparer`1 comparer)
at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable1 source, Func2 keySelector)
at Il2CppDumper.Metadata..ctor(Stream stream)
at Il2CppDumper.FormGUI.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp)
at Il2CppDumper.FormGUI.Dumper(String file, String metadataPath, String outputPath)

Game: Supersus

- Upload executable file and global-metadata.dat: 
I just uploaded it on mediafire, because I don't know how to upload it here, sorry

libil2cpp.so: https://www.mediafire.com/file/7hppssklc9k1bg4/libil2cpp.so/file
global-metadata.dat: https://www.mediafire.com/file/knmcrn6el1i0e7g/global-metadata.dat/file

**Comment by Perfare** [comment]
global-metadata.dat is encrypted
