### ISSUE TITLE
Unsupported version 

### ISSUE THREAD

**Issue by furryhater2008** [Perfare/Il2CppDumper#722]
- latest from /releases ( 6.7.4 )

- 2021.3.17f1

-  System.Collections.Generic.KeyNotFoundException: The given key 'kIl2CppMetadataUsageInvalid' was not present in the dictionary.
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 235
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 121
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98
    
   crash after giving metadata file to dumper, cheatengine still resolves everything 

- https://www.mediafire.com/file/a5khykvplt70j15/GameAssembly.rar/file

**Comment by Perfare** [comment]
It looks like global-metadata.dat is encrypted.
