### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException:

### ISSUE THREAD

**Issue by optimus0701** [Perfare/Il2CppDumper#723]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version: v6.7.40

- Target Unity version (optional)

- Describe the issue: 
   Initializing metadata...
System.Collections.Generic.KeyNotFoundException: The given key 'kIl2CppMetadataUsageInvalid' was not present in the dictionary.
   at Il2CppDumper.Metadata.ProcessingMetadataUsage() in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 235
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 121
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98
Press any key to exit...

- Upload executable file and global-metadata.dat
- global-metadata.dat: https://www.mediafire.com/file/cz1hpq7pfs3dvf9/global-metadata.dat/file
- libil2cpp.so: https://www.mediafire.com/file/s1elxjp9wk3iswa/libil2cpp.so/file

**Comment by Perfare** [comment]
It looks like global-metadata.dat is encrypted.
