### ISSUE TITLE
Sequence contains no matching element

### ISSUE THREAD

**Issue by otokaze** [Perfare/Il2CppDumper#743]
- Il2CppDumper版本
> Il2CppDumper-win-v6.7.40
- 目标Unity版本 (可以不填)

- 问题描述
```text
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at Il2CppDumper.Macho64.Search() in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Macho64.cs:line 95
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 224
ERROR: An error occurred while processing.
Press any key to exit...
```
- 上传可执行文件和global-metadata.dat
[BlueArchive.app.zip](https://github.com/Perfare/Il2CppDumper/files/12403032/BlueArchive.app.zip)

**Comment by LarissaLycoris** [comment]
你好解决了么？我去ida找了 CodeRegistration和MetadataRegistration 也是这个报错

**Comment by HenryQuan** [comment]
你可以尝试 UnityFramework 136 MB 主程序才 70K，什么都没有

**Comment by Perfare** [comment]
ios下可执行文件应该是UnityFramework
