### ISSUE TITLE
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by HarukaMomono** [Perfare/Il2CppDumper#745]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
Il2CppDumper v6.7.40
- Target Unity version (optional)
2021.3.18f1
- Describe the issue
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 29
Searching...
Change il2cpp version to: 29.1
CodeRegistration : b911990
MetadataRegistration : bd84c70
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt64()
   at Il2CppDumper.BinaryStream.ReadPrimitive(Type type) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 112
   at Il2CppDumper.BinaryStream.ReadClass[T]() in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 127
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 197
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 150
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf64.cs:line 97
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 211
ERROR: An error occurred while processing.
Press any key to exit...
- Upload executable file and global-metadata.dat
[files.zip](https://github.com/Perfare/Il2CppDumper/files/12462769/files.zip)

**Comment by vovasicidk** [comment]
i have that issue but after inizialaisation of metadata

**Comment by ImanCol** [comment]
this problem happens to me because the game has empty global-metadata.dat, dummy, 0kb not sure how to get it if the game has obfuscated the metadata, I've seen this before. Any solution to get the missing metadata or is there a way to spit something out without it?
