### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by anggixxx1** [Perfare/Il2CppDumper#746]
> Initializing metadata...
Metadata Version: 24,4
Initializing il2cpp file...
Applying relocations...
WARNING: find .init_proc
ERROR: This file may be protected.
Il2Cpp Version: 24,4
Searching...
CodeRegistration : e3affd0
MetadataRegistration : e3b0050
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 220
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf64.cs:line 97
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 211
ERROR: An error occurred while processing.
Press any key to exit...

~ Il2CppDumper version 6.7.40

I can't dump the lib because an error occurs as in the log above.
64-bit libil2cpp.so

libil2cpp.so https://drive.google.com/file/d/18HbrjxQLTAqVS1FNnkiCeiMjOEcNbbqT/view?usp=sharing
global-metadata.dat https://drive.google.com/file/d/1UR6N3RicMuraGzTxZ0XJfOAyEzL-cyxs/view?usp=sharing

**Comment by Perfare** [comment]
The file you provided has been deleted. If you still have problems, you can consider re-uploading it.
