### ISSUE TITLE
[问题报告] System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by dlbuhtig4096** [Perfare/Il2CppDumper#747]
- Il2CppDumper版本
[v6.7.40](https://github.com/Perfare/Il2CppDumper/releases/tag/v6.7.40)

- 目标Unity版本 (可以不填)
Unity版本: 2020.3.41
IL2CPP版本: 27.1

- 问题描述
游戏经过加壳，查壳显示 Enigma Protector 5.x - 7.0，但档案内字串却写版本是 1.31
脱壳后对分析文件发生 System.IndexOutOfRangeException

- 上传可执行文件和global-metadata.dat
[GameAssembly.dll (已脱壳)](https://drive.google.com/file/d/1dN3xLsW6yJ9L0hrdXXLPYia-mGnI_S_C/view)
[global-metadata.dat](https://drive.google.com/file/d/15q4NdQqSXtvi-mVGf32JT5Vt3xyTDmnV/view)

- Console Output:
```
Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
Change il2cpp version to: 27.1
CodeRegistration : 182e00c60
MetadataRegistration : 182e05040
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2CppExecutor.GetGenericParameteFromIl2CppType(Il2CppType il2CppType) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 309
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 63
   at Il2CppDumper.Il2CppExecutor.GetGenericInstParams(Il2CppGenericInst genericInst) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 188
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 63
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 67
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 266
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...
```

**Comment by Perfare** [comment]
没有在你提供的文件中遇到任何问题，请确认你使用的是最新版本
