### ISSUE TITLE
Arithmetic operation resulted in an overflow.

### ISSUE THREAD

**Issue by lekiet1214** [Perfare/Il2CppDumper#748]
- Il2CppDumper version: win-v6.7.40

- Target Unity version: 2022.3.5f1

- Describe the issue
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
CodeRegistration : 0
MetadataRegistration : 0
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: 18050F920
Input MetadataRegistration: 180569CE0
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 194
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 162
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 237
ERROR: An error occurred while processing.
```
- [Executable file](https://nh0gaming-my.sharepoint.com/:u:/g/personal/nho_nh0gaming_onmicrosoft_com/ESzsQQ_ObthPhAHdZbHa-YkBJkgnc9JzeugnaINFMtFvBQ?e=tqjTuI) and [global-metadata.dat](https://nh0gaming-my.sharepoint.com/:u:/g/personal/nho_nh0gaming_onmicrosoft_com/Ee_-i1U-DThFkmy85QrPUvQBwUqRoTDpC5XNpdxdLF_9Dw?e=JcL8bs)

**Comment by Perfare** [comment]
The executable file is GameAssembly.dll instead of exe file.
