### ISSUE TITLE
Encounter "OverflowException" @ BinaryStream.ReadClassArray[T](Int64 count)

### ISSUE THREAD

**Issue by wolfoops** [Perfare/Il2CppDumper#754]
### Main Error: System.OverflowException: Arithmetic operation resulted in an overflow ###

- Il2CppDumper version 
  = from Il2CppDumper-win-v6.7.40.zip
- Target Unity version (optional)
  = reported 29.1 (?)
- Describe the issue
  = @windows 10, Ryzen 7 3700x, 32G
running output
```
(file path partially edited)
meta: E:\GAMES\Dar___nvoy\Dar__nvoy_Data\il2cpp_data\Metadata\global-metadata.dat (size: 26,893,380 )
dll: GameAssembly.dll (size: 158,137,856 )
============
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
Change il2cpp version to: 29.1
CodeRegistration : 186ce01c0
MetadataRegistration : 188129450
System.OverflowException: Arithmetic operation resulted in an overflow.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 194
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 150
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\PE.cs:line 88
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 211
ERROR: An error occurred while processing.
```
- Upload executable file and global-metadata.dat
[GameAssembly & metadat](https://www.dropbox.com/scl/fi/qi49ac6igqoureo5f15ms/Dar___nvoy.zip?rlkey=xih388mscedgo2do2wykrv3ho&dl=1)

**Comment by Perfare** [comment]
GameAssembly.dll is packed.
