### ISSUE TITLE
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by XavierCruz5106** [Perfare/Il2CppDumper#756]
- Il2CppDumper version: **net7-win-v6.7.40**

- Describe the issue: **when running the executable I supplied the GameAssembly.dll and the global-metadata.dat then the program spits out the this stack trace**

System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadUInt32()
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 45
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98

- Upload executable file and global-metadata.dat
global-metadata.dat is empty?
--GameAssembly.dll https://file.io/CqjKeuG1JYIp

**Comment by Perfare** [comment]
global-metadata.dat is encrypted.
