### ISSUE TITLE
System.OverflowException: Array dimensions exceeded supported range.

### ISSUE THREAD

**Issue by huanglvyuan** [Perfare/Il2CppDumper#757]
Il2CppDumper version:Il2CppDumper-net6-win-v6.7.40

Unity version:2021.3.27

System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 194
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 150
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\PE.cs:line 88
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 211
ERROR: An error occurred while processing.
- Upload executable file and global-metadata.dat
GameAssembly:https://file.io/O5UKV5H11rw5

**Comment by Perfare** [comment]
The file you uploaded has been deleted. If you still have problems, please re-upload the file.

**Comment by Csimbi** [comment]
I have the same problem.
https://github.com/Perfare/Il2CppDumper/issues/780
