### ISSUE TITLE
System.ComponentModel.Win32Exception (126): The specified module could not be found.

### ISSUE THREAD

**Issue by yokeTH** [Perfare/Il2CppDumper#761]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
v6.7.40
- Target Unity version (optional)

- Describe the issue
I try to dump but I got this error

```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (126): The specified module could not be found.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
```
- Upload executable file and global-metadata.dat

**Comment by milo-v** [comment]
Since the OP didn't provide the files, I'd like to submit the ones I'm working on that encounters the same problem: https://drive.google.com/drive/folders/1thTbW7_cDCZyZmc30d2oDUzBrf99liC1?usp=sharing

**Comment by VitorDeF** [comment]
I got the same

`Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
CodeRegistration : 0
MetadataRegistration : 0
Use custom PE loader
System.ComponentModel.Win32Exception (126): Não foi possível encontrar o módulo especificado.
   at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217
ERROR: An error occurred while processing.
Press any key to exit...`

any resolution for the problem?

i think it can be some encryptation issue

**Comment by sinbad28** [comment]
> I got the same
> 
> `Initializing metadata... Metadata Version: 29 Initializing il2cpp file... Il2Cpp Version: 29 Searching... CodeRegistration : 0 MetadataRegistration : 0 Use custom PE loader System.ComponentModel.Win32Exception (126): Não foi possível encontrar o módulo especificado. at Il2CppDumper.PELoader.Load(String fileName) in C:\projects\il2cppdumper\Il2CppDumper\Utils\PELoader.cs:line 48 at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 217 ERROR: An error occurred while processing. Press any key to exit...`
> 
> any resolution for the problem?
> 
> i think it can be some encryptation issue

did you solve it?

**Comment by sinbad28** [comment]
did anyone found a solution?
