### ISSUE TITLE
System.IndexOutOfRangeException: Index was outside the bounds of the array.

### ISSUE THREAD

**Issue by dream811** [Perfare/Il2CppDumper#775]
Note: if you do not provide all of the following information I will directly ignore and close this issue
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
Change il2cpp version to: 29.1
CodeRegistration : 1855d5f60
MetadataRegistration : 185de7420
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2CppExecutor.GetTypeDefinitionFromIl2CppType(Il2CppType il2CppType) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 295
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 101
   at Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 154
   at Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 981
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 55
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 266
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 100
Press any key to exit...
- Il2CppDumper version
6.7.40
- Target Unity version (optional)
29
- Describe the issue
dump error
- Upload executable file and global-metadata.dat

**Comment by Abobo8964** [comment]
have the same error
