### ISSUE TITLE
metadata version 31

### ISSUE THREAD

**Issue by PMTxyzhunter** [Perfare/Il2CppDumper#797]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version 6.7.40

- Target Unity version : 2022.3.33f1

- Describe the issue :
 Initializing metadata...
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[31].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 57
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98
Press any key to exit...

- Upload executable file and global-metadata.dat
arm64 -8va :
libil2cpp.so : https://pixeldrain.com/u/tnnDoUEF
global-metadata.dat : https://pixeldrain.com/u/eJ5hm36X

**Comment by ufrprogramm** [comment]
Also have this problem...

**Comment by jokerart06** [comment]
Many Games already have this problem now. version 31 error. hope perfer will add this soon .

**Comment by ufrprogramm** [comment]
on topic "SamboyCoding" he said Unity 6 dont have  v31 Metadata or what? Its Mean modding of Unity games dead?

**Comment by PenguinCaptain** [comment]
metadata v31 are made from chinese versions of unity

**Comment by trumeetration** [comment]
I also faced this problem. Still no solution?

**Comment by Suyog-Rijal** [comment]
Same issue here

**Comment by YugengWang** [comment]
same problem

**Comment by trumeetration** [comment]
I build my own test app with unity, and it really has metadata v31. Message above about chineese version was not right. 
Unity version to build metadata v31: 2022.3.36f1

May be someone can give guides to update dumper manually 🥇

**Comment by YugengWang** [comment]
I have test 22.3.30f1, It still use metadata version 29. but 22.3.35 use metadata version 31

**Comment by Perfare** [comment]
Support for v31 has been added, but I have only done a small amount of testing. If you have any problems, please open a new issue. I hope to solve them when I have time.

**Comment by jeremyxd228** [comment]
> > Support for v31 has been added, but I have only done a small amount of testing. If you have any problems, please open a new issue. I hope to solve them when I have time.
> 
> I still have: Initializing metadata... System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[31]. at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 57 at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124 at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98 Press any key to exit...

same problem

**Comment by masagrator** [comment]
That means you don't use newest available version which is 6.7.46

**Comment by kavynovipereklady** [comment]
> That means you don't use newest available version which is 6.7.46

Hello. I have newest version 6.7.46 and it doesn't work with il2cpp version 31. I get this error (**Unity version is 2022.3.55f1**)

Initializing metadata...
Metadata Version: 31

Initializing il2cpp file...
Il2Cpp Version: 31

Searching...
CodeRegistration : 182ab8920
MetadataRegistration : 182f355a0

Dumping...
Done!

Generate struct...
Done!

Generate dummy dll...

System.ArgumentNullException: Value cannot be null. (Parameter 'propertyType')
    at Mono.Cecil.Mixin.CheckType(Object type, Argument argument)
    at Mono.Cecil.PropertyDefinition..ctor(String name, PropertyAttributes attributes, TypeReference propertyType)
    at Il2CppDumper.DummyAssemblyGenerator..ctor(Il2CppExecutor il2CppExecutor, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Utils\DummyAssemblyGenerator.cs:line 328
    at Il2CppDumper.DummyAssemblyExporter.Export(Il2CppExecutor il2CppExecutor, String outputDir, Boolean addToken) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\DummyAssemblyExporter.cs:line 14
    at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 271
    at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 99

Can you help ? Thanks
