### ISSUE TITLE
Unity version 31 Error:  Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by jokerart06** [Perfare/Il2CppDumper#799]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version
6.7.45
- Target Unity version (optional)
31
- Describe the issue
Initializing metadata...
Metadata Version: 31
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 31
Searching...
CodeRegistration : 24451f0
MetadataRegistration : 24df920
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 )
   at System.IO.BinaryReader.ReadUInt64()
   at Il2CppDumper.BinaryStream.ReadPrimitive(Type type) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 96
   at Il2CppDumper.BinaryStream.ReadClass[T]() in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 120
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 190
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 150
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 102
   at Il2CppDumper.Elf64.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\Elf64.cs:line 97
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 210
ERROR: An error occurred while processing.
Press any key to exit...

- Upload executable file and global-metadata.dat
libil2cpp.so
https://pixeldrain.com/u/QCof8c25
metadata
https://pixeldrain.com/u/wv6fjDiE

**Comment by jokerart06** [comment]
@Perfare Hope you check this soon my friend. thank you

**Comment by Perfare** [comment]
Same as #798 . It has been fixed.

**Comment by jokerart06** [comment]
> Same as #798 . It has been fixed.

thanks my friend. solve the issues and fixed.

**Comment by hastobetheoneforsomeone** [comment]
not fixed for me
