### ISSUE TITLE
ERROR: Some errors in dumping

### ISSUE THREAD

**Issue by BCouLook** [Perfare/Il2CppDumper#804]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version

- Target Unity version (optional)

- Describe the issue

- Upload executable file and global-metadata.dat

Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Applying relocations...
WARNING: find JNI_OnLoad
ERROR: This file may be protected.
Il2Cpp Version: 29
Searching...
CodeRegistration : a163500
MetadataRegistration : 0
ERROR: No symbol is detected
ERROR: Can't use auto mode to process file, try manual mode.
Input CodeRegistration: a163500
Input MetadataRegistration: a36e890
Dumping...
ERROR: Some errors in dumping
.....
ERROR: Some errors in dumping
Done!
Generate struct...
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Il2CppDumper.Il2CppExecutor.GetTypeDefinitionFromIl2CppType(Il2CppType il2CppType) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 295
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 101
   at Il2CppDumper.Il2CppExecutor.GetTypeName(Il2CppType il2CppType, Boolean addNamespace, Boolean is_nested) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 105
   at Il2CppDumper.Il2CppExecutor.GetTypeDefName(Il2CppTypeDefinition typeDef, Boolean addNamespace, Boolean genericParameter) in C:\projects\il2cppdumper\Il2CppDumper\Utils\Il2CppExecutor.cs:line 154
   at Il2CppDumper.StructGenerator.CreateStructNameDic(Il2CppTypeDefinition typeDef) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 951
   at Il2CppDumper.StructGenerator.WriteScript(String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Outputs\StructGenerator.cs:line 55
   at Il2CppDumper.Program.Dump(Metadata metadata, Il2Cpp il2Cpp, String outputDir) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 265
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 99
Press any key to exit...
[global-metadata.zip](https://github.com/user-attachments/files/16383709/global-metadata.zip)
[libil2cpp.zip.001.zip](https://github.com/user-attachments/files/16383765/libil2cpp.zip.001.zip)
[libil2cpp.zip.002.zip](https://github.com/user-attachments/files/16383767/libil2cpp.zip.002.zip)
[libil2cpp.zip.003.zip](https://github.com/user-attachments/files/16383768/libil2cpp.zip.003.zip)

**Comment by BCouLook** [comment]
Il2CppDumper version Il2CppDumper-win-v6.7.46
