### ISSUE TITLE
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.

### ISSUE THREAD

**Issue by nikitapro225** [Perfare/Il2CppDumper#808]
`Initializing metadata...
Metadata Version: 27
Initializing il2cpp file...
Il2Cpp Version: 27
Searching...
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at Il2CppDumper.SectionHelper.FindMetadataRegistrationV21() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 290
   at Il2CppDumper.SectionHelper.FindMetadataRegistration() in C:\projects\il2cppdumper\Il2CppDumper\Utils\SectionHelper.cs:line 206
   at Il2CppDumper.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\PE.cs:line 85
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 211
ERROR: An error occurred while processing.`

https://www.mediafire.com/file/5yborc5mpp2r0t3/global-metadata.dat/file - metadata
https://www.mediafire.com/file/cotn84lkydomdel/pass_2024.rar/file - Assembly.dll

https://drive.google.com/file/d/1Soh-EdLJY-2HUMC0-rvbcsarxq4iEb6r/view - game

**Comment by nikitapro225** [comment]
![изображение](https://github.com/user-attachments/assets/8e429b9a-e07b-47b2-9f7f-d9051270de86)
