### ISSUE TITLE
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[30].

### ISSUE THREAD

**Issue by SiMaLaoShi** [Perfare/Il2CppDumper#810]
System.NotSupportedException: ERROR: Metadata file supplied is not a supported version[30].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 57
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98

**Comment by Segually** [comment]
i'm having the same issue expect my metadata file is version 31

**Comment by masagrator** [comment]
You don't use the newest version.

https://github.com/Perfare/Il2CppDumper/releases/tag/v6.7.46

**Comment by SiMaLaoShi** [comment]
System.ArgumentException: An item with the same key has already been added. Key: 723124224
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey , TValue , InsertionBehavior )
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](TSource[] , Func`2 , IEqualityComparer`1 )
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 102
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 123
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 97
Press any key to exit...

**Comment by Vinzgh25** [comment]
> You don't use the newest version.
> 
> https://github.com/Perfare/Il2CppDumper/releases/tag/v6.7.46

I'm using this current version, and still same.
