### ISSUE TITLE
initializing Metadata error

### ISSUE THREAD

**Issue by dhruba4900** [Perfare/Il2CppDumper#820]
Initializing metadata...
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 123
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 97
Press any key to exit...

this issues show   that please fix that problem

**Comment by gbraghetti** [comment]
@dhruba4900 look at issue https://github.com/Perfare/Il2CppDumper/issues/817 is the same error. Works for me.

**Comment by bobmis** [comment]
Problem solved? I'm just like you
