### ISSUE TITLE
Incorrect CodeRegistration, Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by misaka-eth** [Perfare/Il2CppDumper#821]
Note: if you do not provide all of the following information I will directly ignore and close this issue

- Il2CppDumper version:: Il2CppDumper-win-v6.7.46

- Target Unity version (optional): 2021.3.29a0

- Describe the issue
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
Il2Cpp Version: 29
Searching...
Change il2cpp version to: 29.1
CodeRegistration : 1863580a0
MetadataRegistration : 18722ce70
System.OverflowException: Array dimensions exceeded supported range.
   at Il2CppDumper.BinaryStream.ReadClassArray[T](Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 187
   at Il2CppDumper.BinaryStream.ReadClassArray[T](UInt64 addr, Int64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 203
   at Il2CppDumper.BinaryStream.ReadClassArray[T](UInt64 addr, UInt64 count) in C:\projects\il2cppdumper\Il2CppDumper\IO\BinaryStream.cs:line 197
   at Il2CppDumper.Il2Cpp.MapVATR[T](UInt64 addr, UInt64 count) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 266
   at Il2CppDumper.Il2Cpp.Init(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 162
   at Il2CppDumper.Il2Cpp.AutoPlusInit(UInt64 codeRegistration, UInt64 metadataRegistration) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Il2Cpp.cs:line 114
   at Il2CppDumper.PE.PlusSearch(Int32 methodCount, Int32 typeDefinitionsCount, Int32 imageCount) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\PE.cs:line 88
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 210
ERROR: An error occurred while processing.
Press any key to exit...

```

Cpp2IL works correctly and shows:
```Got Binary codereg: 0x1863580B0, metareg: 0x18722CE70```

- Upload executable file and global-metadata.dat
https://mega.nz/folder/yuByiLoY#UQsSHsWgDHRlXhvtV7nH7A

**Comment by misaka-eth** [comment]
https://github.com/Perfare/Il2CppDumper/blob/4741d46ba9cd6159c5d853eb9d6fc48b4bfa2b1a/Il2CppDumper/Il2Cpp/Il2Cpp.cs#L73

Solved. Incorrect version detection. I removed switch to 29.1 and it worked for me

**Comment by Csimbi** [comment]
I have the same problem.
https://github.com/Perfare/Il2CppDumper/issues/780
Could you release a new build with this fix, please?
Thank you!
