### ISSUE TITLE
Not valid metadata file?

### ISSUE THREAD

**Issue by yuasmink** [Perfare/Il2CppDumper#822]
Ll2cppdumper version 6.7.46.

Initializing metadata...
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 123
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 97
Press any key to exit...
[global-metadata.zip](https://github.com/user-attachments/files/17347962/global-metadata.zip)
https://www.mediafire.com/file/ow6qyot0vbblneu/libil2cpp.zip/file

**Comment by c01ns** [comment]
you can fix The first 6 bytes，and try it again
![image](https://github.com/user-attachments/assets/2fccac12-1541-4bdd-8d7a-e267b94cf3d2)

**Comment by usoppu** [comment]
> you can fix The first 6 bytes，and try it again ![image](https://github.com/user-attachments/assets/2fccac12-1541-4bdd-8d7a-e267b94cf3d2)

what does that even mean? your screen grab shows his current files' hex values. what should they be? how to "FIX" them?

**Comment by xADDBx** [comment]
> > you can fix The first 6 bytes，and try it again ![image](https://github.com/user-attachments/assets/2fccac12-1541-4bdd-8d7a-e267b94cf3d2)
> 
> what does that even mean? your screen grab shows his current files' hex values. what should they be? how to "FIX" them?

Il2CppDumper does the following:

```cs
var sanity = ReadUInt32();
if (sanity != 0xFAB11BAF)
{
    throw new InvalidDataException("ERROR: Metadata file supplied is not valid metadata file.");
}
var version = ReadInt32();
if (version < 0 || version > 1000)
{
    throw new InvalidDataException("ERROR: Metadata file supplied is not valid metadata file.");
}
```

Meaning `fixing the first few bytes`  would mean changing them to have the proper magic number. I would say that this probably won't help much, and the global-metadata.dat is probably encrypted in some way.
