### ISSUE TITLE
ERROR: Metadata file supplied is not a supported version[31].

### ISSUE THREAD

**Issue by bajiaoxiansheng5542** [Perfare/Il2CppDumper#827]
请注意：如果你没有提供以下所有信息我将会直接无视并关闭这个issue

- Il2CppDumper版本
- Il2CppDumper-win-v6.7.40

- 目标Unity版本 (可以不填)

- 问题描述 
- ERROR: Metadata file supplied is not a supported version[31].
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 57
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 124
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 98
Press any key to exit...

- 上传可执行文件和global-metadata.dat
[GameAssembly.zip](https://github.com/user-attachments/files/17637117/GameAssembly.zip)
[global-metadata.zip](https://github.com/user-attachments/files/17637119/global-metadata.zip)

**Comment by wrliwa** [comment]
一样的问题

**Comment by Sovenok-Hacker** [comment]
I have this error too

**Comment by masagrator** [comment]
https://github.com/Perfare/Il2CppDumper/issues/802#issuecomment-2336289903
