### ISSUE TITLE
ERROR: Metadata file supplied is not valid metadata file.

### ISSUE THREAD

**Issue by darshanraok** [Perfare/Il2CppDumper#832]
- Il2CppDumper version **6.7.46**

- Target Unity version (optional) **i dont know**

- Describe the issue - Initializing metadata...
System.IO.InvalidDataException: ERROR: Metadata file supplied is not valid metadata file.
   at Il2CppDumper.Metadata..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\Il2Cpp\Metadata.cs:line 48
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 123
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 97
Press any key to exit...

- Upload executable file and global-metadata.dat
[libanddat.zip](https://github.com/user-attachments/files/17965130/libanddat.zip)

**Comment by c01ns** [comment]
global-metadata.dat is encrypt，You should decrypt it yourself

**Comment by darshanraok** [comment]
> global-metadata.dat is encrypt，You should decrypt it yourself

How to decrypt

**Comment by Opi-T31** [comment]
Use Game Guardian to decrypt the global-metadata.dat and libil2cpp.so. Listen and follow what this guy is doing in the video step by step https://www.youtube.com/watch?v=Yxzr78wM-6c

**Comment by dllhpdev-dotcom** [comment]
а как на пк билде расшифровать global-metadata.dat?

**Comment by omairahmed699-crypto** [comment]
my files are decrypted but still shows same error, my metadata starts with the magic bytes too
