### ISSUE TITLE
System.InvalidOperationException: Sequence contains no matching element

### ISSUE THREAD

**Issue by masagrator** [Perfare/Il2CppDumper#835]
- Il2CppDumper version: 6.7.46

- Target Unity version: 2021.3.34.f1

- Describe the issue:
```
Initializing metadata...
Metadata Version: 29
Initializing il2cpp file...
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 , Func`2 )
   at Il2CppDumper.NSO.MapVATR(UInt64 addr) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\NSO.cs:line 205
   at Il2CppDumper.NSO..ctor(Stream stream) in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\NSO.cs:line 95
   at Il2CppDumper.NSO.UnCompress() in C:\projects\il2cppdumper\Il2CppDumper\ExecutableFormats\NSO.cs:line 320
   at Il2CppDumper.Program.Init(String il2cppPath, String metadataPath, Metadata& metadata, Il2Cpp& il2Cpp) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 140
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 97
Press any key to exit...
```

- Upload executable file and global-metadata.dat
https://drive.google.com/file/d/1c07-0fADl7hYxgFX_QkIK_0l7CD7p1_X/view?usp=drive_link

My educated guess is that they moved from RELA to RELR in recent SDK updates, and tool doesn't support parsing it. Older updates of game work fine.

**Comment by masagrator** [comment]
Next update, the same issue

https://drive.google.com/file/d/1CHq1oAURl3-I2rJJxZbFpMCgFz7W3sQ6/view?usp=sharing

**Comment by masagrator** [comment]
Another game - the same issue

https://drive.google.com/file/d/1WZboZ7t6CHyB7yJkd6k6xUQ316c719eM/view?usp=sharing

**Comment by masagrator** [comment]
Someone found that it works fine if you convert NSO to ELF beforehand with nx2elf
