### ISSUE TITLE
Error: Some errors in dumping

### ISSUE THREAD

**Issue by NeOAnderson** [Perfare/Il2CppDumper#99]
```
Is the Unity version greater than or equal to 2018.3?
1.Yes 2.No
Initializing metadata...
Select Mode: 1.Manual 2.Auto 3.Auto(Advanced) 4.Auto(Plus) 5.Auto(Symbol)
Initializing il2cpp file...
Searching...
Dumping...
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
ERROR: Some errors in dumping
System.NullReferenceException: Object reference not set to an instance of an object.
   at Il2CppDumper.Program.Dump() in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 515
   at Il2CppDumper.Program.Main(String[] args) in C:\projects\il2cppdumper\Il2CppDumper\Program.cs:line 65
Press any key to exit...

```

[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/2842915/GameAssembly.zip)

not sure what i'm doing wrong, i tried all extraction methods and each one says various errors usually along the lines of not being able to do it and try another method or the above message

**Comment by Perfare** [comment]
Please upload global-metadata.dat

**Comment by NeOAnderson** [comment]
Sorry! I have re-uploaded the gameassembly.zip with the meta inside too. 

[GameAssembly.zip](https://github.com/Perfare/Il2CppDumper/files/2845692/GameAssembly.zip)

**Comment by Perfare** [comment]
work fine.

**Comment by NeOAnderson** [comment]
Sorry but can you please explain how you got it to work? It did not work for me, i can record and send you a video of it not working?

**Comment by NeOAnderson** [comment]
![error](https://user-images.githubusercontent.com/981730/52515712-2188e380-2c17-11e9-8253-7ef076272aa5.png)

**Comment by NeOAnderson** [comment]
that is what it would say on every method i try for extraction, if I just press enter without a number when it asks for the extraction method, it gives me the error i posted in the first post otherwise all extraction methods give the above error... ? =\
